name: ar_live_ais
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0
  awesome_dialog: ^2.1.0
  top_snackbar_flutter: ^1.0.0
  multi_image_picker: ^4.8.1
  font_awesome_flutter: ^9.1.0
  flex_color_picker: ^2.1.2
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  flutter_bloc: ^7.1.0
  http: ^0.13.3
  fluttertoast: ^8.0.8
  flutter_countdown_timer: ^4.1.0
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  web_socket_channel: ^2.1.0
  dio: ^4.0.0
  flutter_login_facebook: ^1.1.0
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - bank/
